uploads = []

[[generated]]
id = "xEQhhAhcfYDtzWuA2M-nm"
uri = "file://assets/images/panda-stamp-13.png"
type = "image"
title = "generated_image"

[[generated]]
id = "GNxRwHqNzd-oz7PCLa06l"
uri = "file://assets/images/panda-stamp-14.png"
type = "image"
title = "generated_image"

[[generated]]
id = "O4rQ1Z4fXufE-EYGCmt0D"
uri = "file://assets/images/panda-stamp-15.png"
type = "image"
title = "generated_image"

[[generated]]
id = "RP-dCdcZ57GkZKYnNLYx2"
uri = "file://assets/images/panda-stamp-16.png"
type = "image"
title = "generated_image"

[[generated]]
id = "c5YrP5D602QBylr8opzVN"
uri = "file://assets/images/panda-stamp-17.png"
type = "image"
title = "generated_image"

[[generated]]
id = "d_ef0ABeQ2QQ-fE0Pmvy8"
uri = "file://assets/images/panda-stamp-18.png"
type = "image"
title = "generated_image"

[[generated]]
id = "E1DY9LzQ_4VipQLofBfoM"
uri = "file://assets/images/panda-stamp-19.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Nf3V5YUHJUbUN64FgINv_"
uri = "file://assets/images/panda-stamp-20.png"
type = "image"
title = "generated_image"

[[generated]]
id = "3krPxcO0CxJrsKjETWJuE"
uri = "file://assets/images/panda-stamp-21.png"
type = "image"
title = "generated_image"

[[generated]]
id = "MSyjM4xmC36I9UFvIz5P7"
uri = "file://assets/images/panda-stamp-22.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ZV0KPfScGWFR1IEB97_Mq"
uri = "file://assets/images/panda-stamp-23.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Yd0tbwt3HBKfbEIHgJktE"
uri = "file://assets/images/panda-stamp-24.png"
type = "image"
title = "generated_image"

[[generated]]
id = "ZMd4UEy9O62oqq7Nml9kK"
uri = "file://assets/images/panda-stamp-25.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Ih-CF6a7gUn3HFKNqM2rf"
uri = "file://assets/images/panda-stamp-26.png"
type = "image"
title = "generated_image"

[[generated]]
id = "184HVciHfQnk7Oh_7EctV"
uri = "file://assets/images/panda-stamp-27.png"
type = "image"
title = "generated_image"

[[generated]]
id = "jZIrjcDjnrOF3LxjqoS-Y"
uri = "file://assets/images/panda-stamp-28.png"
type = "image"
title = "generated_image"

[[generated]]
id = "MsDJsxuxAGpO0kOPQAfUm"
uri = "file://assets/images/panda-stamp-29.png"
type = "image"
title = "generated_image"

[[generated]]
id = "84PzWYAH9fsYYJjZJkW6G"
uri = "file://assets/images/panda-stamp-30.png"
type = "image"
title = "generated_image"

[[generated]]
id = "RMN4liGWesBnhOtdFzTqy"
uri = "file://assets/images/panda-stamp-31.png"
type = "image"
title = "generated_image"

[[generated]]
id = "BNPU4RWdCfhcVDosVQIrb"
uri = "file://assets/images/panda-stamp-32.png"
type = "image"
title = "generated_image"

[[generated]]
id = "URbO6veqR3qYPWyRfIyi9"
uri = "file://assets/images/panda-stamp-33.png"
type = "image"
title = "generated_image"

[[generated]]
id = "E1eN4FXfAx-oVcNyBydXf"
uri = "file://assets/images/panda-stamp-34.png"
type = "image"
title = "generated_image"

[[generated]]
id = "JpwjV6vkBpEUPxrlNibU0"
uri = "file://assets/images/panda-stamp-35.png"
type = "image"
title = "generated_image"

[[generated]]
id = "3oN084TLXbKo5xhS0S2WL"
uri = "file://assets/images/panda-stamp-36.png"
type = "image"
title = "generated_image"

[[generated]]
id = "cFrMNNa7Br0EQKJg_Q_Q3"
uri = "file://assets/images/panda-stamp-37.png"
type = "image"
title = "generated_image"

[[generated]]
id = "c7sMuo4BdcCrrFTOoqd0f"
uri = "file://assets/images/panda-stamp-38.png"
type = "image"
title = "generated_image"

[[generated]]
id = "__gwSYOt8MTz6iDILoJGI"
uri = "file://assets/images/panda-stamp-39.png"
type = "image"
title = "generated_image"

[[generated]]
id = "NTlQKKDqEhM7vWye-OR31"
uri = "file://assets/images/panda-stamp-40.png"
type = "image"
title = "generated_image"

[[generated]]
id = "wC_gmu-JxsF-YptBlKGS4"
uri = "file://assets/images/panda-stamp-41.png"
type = "image"
title = "generated_image"

[[generated]]
id = "HUhNuXLM55r550eiDsUg4"
uri = "file://assets/images/panda-stamp-42.png"
type = "image"
title = "generated_image"

[[generated]]
id = "bFqogAuwilvg7f8EsZsaV"
uri = "file://assets/images/panda-stamp-43.png"
type = "image"
title = "generated_image"

[[generated]]
id = "tJ79PUTq0slvYvvXNB8pC"
uri = "file://assets/images/panda-stamp-44.png"
type = "image"
title = "generated_image"

[[generated]]
id = "_0tnCBpOeFEG8YKEmr_Ze"
uri = "file://assets/images/panda-stamp-45.png"
type = "image"
title = "generated_image"

[[generated]]
id = "xnBh-vID5iTLvqwCVOHq1"
uri = "file://assets/images/panda-stamp-46.png"
type = "image"
title = "generated_image"

[[generated]]
id = "aaLFaiK44_GWsDQ4zBB4Z"
uri = "file://assets/images/panda-stamp-47.png"
type = "image"
title = "generated_image"

[[generated]]
id = "1OY8LYgqN76ik0yu83OFD"
uri = "file://assets/images/panda-stamp-48.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Nk-0eapK6uAkKnakOOS7P"
uri = "file://assets/images/panda-stamp-49.png"
type = "image"
title = "generated_image"

[[generated]]
id = "oNY28lxT2falGxyUynEkA"
uri = "file://assets/images/panda-stamp-50.png"
type = "image"
title = "generated_image"

[[generated]]
id = "aH4M3ehxm2nMJsA-uyC-0"
uri = "file://assets/images/panda-stamp-51.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Zib3u1snbkwqXlrzqMk97"
uri = "file://assets/images/panda-stamp-52.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Bauu2UVEFMV9-YIqpSGZb"
uri = "file://assets/images/panda-stamp-53.png"
type = "image"
title = "generated_image"

[[generated]]
id = "7RJcbfBiFODt5z4DUNsiU"
uri = "file://assets/images/panda-stamp-54.png"
type = "image"
title = "generated_image"

[[generated]]
id = "VRxtqfoEzf5Cwyd9ahNRT"
uri = "file://assets/images/panda-stamp-55.png"
type = "image"
title = "generated_image"

[[generated]]
id = "zP4wL84oIpeC1N7ZAY7KP"
uri = "file://assets/images/panda-stamp-56.png"
type = "image"
title = "generated_image"

[[generated]]
id = "hPIzXuxBZYJVuUO5ta_kq"
uri = "file://assets/images/panda-stamp-57.png"
type = "image"
title = "generated_image"

[[generated]]
id = "u0yr6HMHFMurwElcEF3lL"
uri = "file://assets/images/panda-stamp-58.png"
type = "image"
title = "generated_image"

[[generated]]
id = "TDCJt4UDbWJYWQmux-o4T"
uri = "file://assets/images/panda-stamp-59.png"
type = "image"
title = "generated_image"

[[generated]]
id = "81ecbRvkkOoN8nr68ln8D"
uri = "file://assets/images/panda-stamp-60.png"
type = "image"
title = "generated_image"

[[generated]]
id = "yX4gep5TwbzgU-tvHCyTw"
uri = "file://assets/images/onboarding-1.png"
type = "image"
title = "panda reading book"

[[generated]]
id = "Zb5k3V9nAC6rKP72HSRM4"
uri = "file://assets/images/onboarding-2.png"
type = "image"
title = "panda with headphones"

[[generated]]
id = "X5tnCw_w9B6YI_KIiOJ-u"
uri = "file://assets/images/onboarding-3.png"
type = "image"
title = "panda sprint stamp rally"

[[generated]]
id = "AkD_6i_M-z5qOII8I_MKa"
uri = "file://assets/images/panda-stamp-tutorial.png"
type = "image"
title = "panda astronaut stamp"

[[generated]]
id = "DPD1On_sZaIxNWlIJAEpS"
uri = "file://assets/images/panda-stamp-special-2.png"
type = "image"
title = "panda fb special 2"

[[generated]]
id = "BWbGPr2fwuVBpAanPbBvj"
uri = "file://assets/images/panda-stamp-special-3.png"
type = "image"
title = "panda fb special 3"

[[generated]]
id = "LgcCEidoo3trwtUs2lJ2S"
uri = "file://assets/images/panda-stamp-special-4.png"
type = "image"
title = "panda fb special 4"

[[generated]]
id = "5e2AneTRIX57U_izj4vpF"
uri = "file://assets/images/panda-stamp-special-5.png"
type = "image"
title = "panda fb special 5"

[[generated]]
id = "1nXHxrL-Uaho4-arsqRen"
uri = "file://assets/images/panda-stamp-special-6.png"
type = "image"
title = "panda fb special 6"

[[generated]]
id = "-sVS-zPMLBqPfxK7zf7DD"
uri = "file://assets/images/panda-stamp-special-7.png"
type = "image"
title = "panda fb special 7"

[[generated]]
id = "YMjm9INtsFTZ0rja7peLN"
uri = "file://assets/images/panda-stamp-special-8.png"
type = "image"
title = "panda fb special 8"

[[generated]]
id = "Mwg-WwnIJ9BQ1Hc0uxj2i"
uri = "file://assets/images/panda-stamp-special-9.png"
type = "image"
title = "panda fb special 9"

[[generated]]
id = "3bLX2QIPFToYTl62a_eAn"
uri = "file://assets/images/panda-stamp-special-10.png"
type = "image"
title = "panda fb special 10"

[[generated]]
id = "x4PnFxZLeBcCye_p1616Y"
uri = "file://assets/images/panda-stamp-special-11.png"
type = "image"
title = "panda fb special 11"

[[generated]]
id = "ahjhoxrWW3aWshYLpolB1"
uri = "file://assets/images/panda-stamp-special-12.png"
type = "image"
title = "panda fb special 12"

[[generated]]
id = "s5XC6r3X7ikLYhOIaQDlL"
uri = "file://assets/images/panda-stamp-special-13.png"
type = "image"
title = "panda fb special 13"

[[generated]]
id = "8H19U96JQaWsnhzEXBlC0"
uri = "file://assets/images/panda-stamp-special-14.png"
type = "image"
title = "panda fb special 14"

[[generated]]
id = "3GjnUFjlcMqpJOUIigwvs"
uri = "file://assets/images/panda-stamp-special-15.png"
type = "image"
title = "panda fb special 15"

[[generated]]
id = "HkiGhcdVxlv0jpklagUii"
uri = "file://assets/images/panda-stamp-special-16.png"
type = "image"
title = "panda fb special 16"

[[generated]]
id = "QU-WJ3RNDuFnym_7__sbb"
uri = "file://assets/images/panda-stamp-special-17.png"
type = "image"
title = "panda fb special 17"

[[generated]]
id = "IHmqSs6tHfvOa8OjfX5uc"
uri = "file://assets/images/panda-stamp-special-19.png"
type = "image"
title = "panda fb special 19"

[[generated]]
id = "MS-9QqMDmXOYRJDpEL7IS"
uri = "file://assets/images/panda-stamp-special-20.png"
type = "image"
title = "panda fb special 20"

[[generated]]
id = "WfoWVfNyi1UmC--fu1m7s"
uri = "file://assets/images/panda-stamp-special-21.png"
type = "image"
title = "panda fb special 21"

[[generated]]
id = "6oGFqoduFCnWLL9um12RO"
uri = "file://assets/images/panda-stamp-special-22.png"
type = "image"
title = "panda fb special 22"

[[generated]]
id = "aRKTuuhVRdqBcMCm4xkzu"
uri = "file://assets/images/panda-stamp-special-23.png"
type = "image"
title = "panda fb special 23"

[[generated]]
id = "QyDee_eyujTo83DsxkIQo"
uri = "file://assets/images/panda-stamp-special-24.png"
type = "image"
title = "panda fb special 24"

[[generated]]
id = "UAOwgMlMmte51Ree0JQE3"
uri = "file://assets/images/panda-stamp-special-25.png"
type = "image"
title = "panda fb special 25"

[[generated]]
id = "1oI22MCHzLDeB9qdWWnRt"
uri = "file://assets/images/panda-stamp-special-26.png"
type = "image"
title = "panda fb special 26"

[[generated]]
id = "TQg74PCU6RSPJHGu_QeYt"
uri = "file://assets/images/panda-stamp-special-27.png"
type = "image"
title = "panda fb special 27"

[[generated]]
id = "Mh1QPzo48Z2cl_0tyEgyM"
uri = "file://assets/images/panda-stamp-special-28.png"
type = "image"
title = "panda fb special 28"

[[generated]]
id = "t5RUEPlt2oT6zI1p6Mflz"
uri = "file://assets/images/panda-stamp-special-29.png"
type = "image"
title = "panda fb special 29"

[[generated]]
id = "oBigRU-Y0CqNRCj7ki37t"
uri = "file://assets/images/panda-stamp-special-30.png"
type = "image"
title = "panda fb special 30"

[[generated]]
id = "C_HswYICsKJJD5iy6STf_"
uri = "file://assets/images/panda-stamp-special-31.png"
type = "image"
title = "panda fb special 31"

[[generated]]
id = "WJo5ChFK4e5z03SiTlZtK"
uri = "file://assets/images/panda-stamp-special-32.png"
type = "image"
title = "panda fb special 32"

[[generated]]
id = "-uJyUwumd5czqE538soqC"
uri = "file://assets/images/panda-stamp-special-33.png"
type = "image"
title = "panda fb special 33"

[[generated]]
id = "h2fOeoQZ2GYJGX2GRTZnZ"
uri = "file://assets/images/panda-stamp-special-34.png"
type = "image"
title = "panda fb special 34"

[[generated]]
id = "YqJxGCGW1NB-Ogx07nQ75"
uri = "file://assets/images/panda-stamp-special-35.png"
type = "image"
title = "panda fb special 35"

[[generated]]
id = "aTfPPj4PQY9ERZ7jypi-Y"
uri = "file://assets/images/panda-stamp-special-18.png"
type = "image"
title = "panda fb special 18"

[[outputs]]
id = "25ttI0-awxEyfFdb-9QYb"
uri = "file://assets/images/icon.png"
type = "image"
title = "アイコン（HSK文字大きめ）"
